### ISSUE TITLE
After RC2, Standup.app broken

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup-MacOS#14]
Bitcoin Standup has been working on my laptop for a few weeks on main net fine, but today is first boot since the 0.20.0rc2 change, and it is not booting up bitcoin-core nor is it allowing upgrade.

**Comment by ChristopherA** [comment]
I had to do standdown then standup again, which of course also deleted the onion info for the node. Should be some way to stand down but preserve onion info.

**Comment by Fonta1n3** [comment]
This is fixed in the #13 , Standing down intentionally removes everything. The best way to keep the hidden services intact is to simply delete `~/StandUp` and then use the StandUp button again as this will have no effect on the hidden services. We can certainly add more options to the kill switches so hidden service remains.

**Comment by Fonta1n3** [comment]
Seeing as this raises two issues one of which is resolved on #13 I will close this and reopen a dedicated issue for more fine tuned kill switches.
